# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 200)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 240))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditFile = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditFile.setMinimumSize(QtCore.QSize(400, 28))
        self.lineEditFile.setObjectName("lineEditFile")
        self.gridLayout.addWidget(self.lineEditFile, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(150, 25, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setMinimumSize(QtCore.QSize(160, 0))
        self.startButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startButton.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 1, 3, 1, 1)
        self.selectDirButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectDirButton.setMinimumSize(QtCore.QSize(160, 0))
        self.selectDirButton.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.selectDirButton.setObjectName("selectDirButton")
        self.gridLayout.addWidget(self.selectDirButton, 0, 1, 1, 1)
        self.lineEditDir = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDir.setMinimumSize(QtCore.QSize(400, 28))
        self.lineEditDir.setObjectName("lineEditDir")
        self.gridLayout.addWidget(self.lineEditDir, 0, 0, 1, 1)
        self.selectFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectFileButton.setMinimumSize(QtCore.QSize(160, 0))
        self.selectFileButton.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.selectFileButton.setObjectName("selectFileButton")
        self.gridLayout.addWidget(self.selectFileButton, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 71))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Старт"))
        self.selectDirButton.setText(_translate("MainWindow", "выберите папку"))
        self.selectFileButton.setText(_translate("MainWindow", "выберите файл"))
        self.label.setText(_translate("MainWindow", "Выбор из проводника пути к файлу или директории"))
